# Generated by Django 5.2.1 on 2025-05-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audience", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                ("desc", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "requirement",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Условия"
                    ),
                ),
                ("date_start", models.DateTimeField(verbose_name="Начало")),
                ("date_end", models.DateTimeField(verbose_name="Окончание")),
                ("is_free", models.BooleanField(verbose_name="Бесплатно")),
                (
                    "location",
                    models.TextField(blank=True, verbose_name="Место проведения"),
                ),
                (
                    "registration_link",
                    models.URLField(blank=True, verbose_name="Ссылка на регистрацию"),
                ),
                (
                    "audience",
                    models.ManyToManyField(
                        to="audience.subaudience", verbose_name="Аудитория"
                    ),
                ),
                (
                    "organizer",
                    models.ManyToManyField(
                        to="organizations.organization", verbose_name="Организация"
                    ),
                ),
            ],
        ),
    ]
