version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: aggregator_assistance_django
    container_name: aggregator_assistance_django
    volumes:
      - aggregator_assistance_static:/aggregator_assistance/static
      - aggregator_assistance_media:/aggregator_assistance/media
      - aggregator_assistance_fixtures:/aggregator_assistance/fixtures_temp
    expose:
      - "8050"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    command: sh -c "python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn config.wsgi -b 0.0.0.0:8050"

  nginx:
    restart: always
    build:
      context: ./docker/nginx/
      dockerfile: ./Dockerfile
    image: aggregator_assistance_nginx
    container_name: aggregator_assistance_nginx
    ports:
      - "85:85"
    volumes:
      - aggregator_assistance_static:/aggregator_assistance/static
      - aggregator_assistance_media:/aggregator_assistance/media
      - aggregator_assistance_fixtures:/aggregator_assistance/fixtures
    depends_on:
      - django

volumes:
  aggregator_assistance_static:
  aggregator_assistance_media:
  aggregator_assistance_fixtures:

