# Generated by Django 5.2.1 on 2025-05-12 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryOrg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="")),
                ("slug", models.SlugField(max_length=100, verbose_name="URL")),
                ("desc", models.CharField(blank=True, max_length=500, verbose_name="")),
                (
                    "img",
                    models.ImageField(
                        blank=True, null=True, upload_to=None, verbose_name=""
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Город")),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Область")),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("desc", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "requirement",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Условия получения"
                    ),
                ),
                ("is_free", models.BooleanField(verbose_name="Бесплатно")),
                (
                    "is_online_available",
                    models.BooleanField(verbose_name="is online available"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TargetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CityRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Округ")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100, verbose_name="Улица")),
                ("house", models.CharField(max_length=20, verbose_name="Дом")),
                (
                    "apartment",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Квартира"
                    ),
                ),
                (
                    "city_region",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.cityregion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("GOV", "Государственная"),
                            ("COMM", "Коммерческая"),
                            ("NPO", "НКО"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logos/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "category_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.categoryorg",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GeoLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField(verbose_name="Широта")),
                ("longitude", models.FloatField(verbose_name="Долгота")),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geo_location",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Геолокация",
                "verbose_name_plural": "Геолокации",
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("phone", "Телефон"),
                            ("email", "Email"),
                            ("address", "Адрес"),
                            ("website", "Сайт"),
                            ("social", "Соцсеть"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип контакта",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Значение")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Основной контакт"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=0, verbose_name="Приоритет"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["-is_primary", "priority"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.address",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "address")},
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.ManyToManyField(
                blank=True,
                through="organizations.OrganizationAddress",
                to="organizations.address",
                verbose_name="Адрес",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_main_service", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "duration",
                    models.DurationField(
                        null=True, verbose_name="Длительность оказания"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.service",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "service")},
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                through="organizations.OrganizationService",
                to="organizations.service",
                verbose_name="Услуги",
            ),
        ),
        migrations.CreateModel(
            name="SocialMediaProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("vk", "VKontakte"),
                            ("fb", "Facebook"),
                            ("ig", "Instagram"),
                            ("tg", "Telegram"),
                            ("yt", "YouTube"),
                            ("oth", "Другое"),
                        ],
                        max_length=3,
                        verbose_name="Платформа",
                    ),
                ),
                ("profile_url", models.URLField(verbose_name="Ссылка на профиль")),
                (
                    "followers",
                    models.PositiveIntegerField(default=0, verbose_name="Подписчики"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Верифицирован"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_profiles",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Соцсеть",
                "verbose_name_plural": "Соцсети",
            },
        ),
        migrations.CreateModel(
            name="SubRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Муниципалитеты"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.region",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="sub_region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.subregion",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="audience",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.targetgroup",
                verbose_name="Аудитория",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(default=True, verbose_name="Бесплатно"),
                ),
                (
                    "participation_conditions",
                    models.TextField(blank=True, verbose_name="Условия участия"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "target_groups",
                    models.ManyToManyField(
                        blank=True,
                        to="organizations.targetgroup",
                        verbose_name="Целевые группы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа",
                "verbose_name_plural": "Программы",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="target_groups",
            field=models.ManyToManyField(
                blank=True,
                to="organizations.targetgroup",
                verbose_name="Целевые группы",
            ),
        ),
        migrations.CreateModel(
            name="WorkingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                (
                    "opens_at",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время открытия"
                    ),
                ),
                (
                    "closes_at",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время закрытия"
                    ),
                ),
                (
                    "is_round_the_clock",
                    models.BooleanField(default=False, verbose_name="Круглосуточно"),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Выходной"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Комментарий"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_schedules",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "График работы",
                "verbose_name_plural": "Графики работы",
                "ordering": ["day_of_week"],
            },
        ),
    ]
