# Generated by Django 5.2.1 on 2025-05-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assistance", "0001_initial"),
        ("servises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Город")),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Область")),
            ],
        ),
        migrations.CreateModel(
            name="CityRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Округ")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100, verbose_name="Улица")),
                ("house", models.CharField(max_length=20, verbose_name="Дом")),
                (
                    "apartment",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Квартира"
                    ),
                ),
                (
                    "city_region",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.cityregion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("GOV", "Государственная"),
                            ("COMM", "Коммерческая"),
                            ("NPO", "НКО"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "update_date",
                    models.DateField(
                        auto_now=True, verbose_name="Дата обновления данных"
                    ),
                ),
                (
                    "address",
                    models.ManyToManyField(
                        to="organizations.address", verbose_name="Адрес"
                    ),
                ),
                (
                    "assistance",
                    models.ManyToManyField(
                        related_name="Помощь",
                        to="assistance.assistance",
                        verbose_name="Категории",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="Услуги",
                        to="servises.servis",
                        verbose_name="Услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Муниципалитеты"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.region",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="sub_region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.subregion",
            ),
        ),
    ]
