# Generated by Django 5.2.1 on 2025-05-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audience", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
            ],
        ),
        migrations.CreateModel(
            name="Lawful",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("link", models.URLField(blank=True, verbose_name="Ссылка на закон")),
            ],
        ),
        migrations.CreateModel(
            name="Assistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("desc", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "requirement",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Условия получения"
                    ),
                ),
                (
                    "support_period",
                    models.DateField(verbose_name="Срок действия помощи"),
                ),
                (
                    "audience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audience.subaudience",
                        verbose_name="Аудитория",
                    ),
                ),
                (
                    "documents",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assistance.document",
                        verbose_name="Документы",
                    ),
                ),
                (
                    "lawful",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assistance.lawful",
                        verbose_name="Основания",
                    ),
                ),
            ],
        ),
    ]
