# Generated by Django 5.2.1 on 2025-05-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("subtitle", models.TextField(verbose_name="Подзаголовок")),
                (
                    "button_text",
                    models.CharField(
                        default="Начать проверку",
                        max_length=50,
                        verbose_name="Текст кнопки",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HomePageStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("value", models.IntegerField(verbose_name="Значение")),
            ],
        ),
    ]
