# Generated by Django 5.2.1 on 2025-05-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Целевая группа"),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Описание"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Подгруппа")),
                (
                    "desc",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Описание"
                    ),
                ),
                (
                    "audience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audience.audience",
                    ),
                ),
            ],
        ),
    ]
